# Generated by Django 4.2.16 on 2024-11-29 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DomushnikApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='adminlog',
            options={'verbose_name': 'Лог администратора', 'verbose_name_plural': 'Логи администратора'},
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Удобство', 'verbose_name_plural': 'Удобства'},
        ),
        migrations.AlterModelOptions(
            name='backup',
            options={'verbose_name': 'Резервная копия', 'verbose_name_plural': 'Резервные копии'},
        ),
        migrations.AlterModelOptions(
            name='moderatorlog',
            options={'verbose_name': 'Лог модератора', 'verbose_name_plural': 'Логи модераторов'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'verbose_name': 'Тип уведомления', 'verbose_name_plural': 'Типы уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='propertyfeature',
            options={'verbose_name': 'Характеристика недвижимости', 'verbose_name_plural': 'Характеристики недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='propertyphoto',
            options={'verbose_name': 'Фото недвижимости', 'verbose_name_plural': 'Фотографии недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Тип недвижимости', 'verbose_name_plural': 'Типы недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренда'},
        ),
        migrations.AlterModelOptions(
            name='rentalapplication',
            options={'verbose_name': 'Заявка на аренду', 'verbose_name_plural': 'Заявки на аренду'},
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Штат/Область'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.TextField(verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Удобство'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='file_path',
            field=models.CharField(max_length=255, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='moderatorlog',
            name='action',
            field=models.TextField(verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='moderatorlog',
            name='action_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='moderatorlog',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_logs', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DomushnikApp.notificationtype', verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название типа уведомления'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='DomushnikApp.rental', verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DomushnikApp.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='DomushnikApp.amenity', verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='property',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Доступно'), ('rented', 'Арендовано'), ('under_maintenance', 'На ремонте')], default='available', max_length=20, verbose_name='Статус доступности'),
        ),
        migrations.AlterField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='Балкон'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='energy_efficiency_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс энергопотребления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Меблированное'),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип отопления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='internet_access',
            field=models.BooleanField(default=False, verbose_name='Доступ в интернет'),
        ),
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Арендодатель'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_amenities',
            field=models.TextField(blank=True, null=True, verbose_name='Близлежащие удобства'),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Можно с животными'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за месяц'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('good', 'Хорошее'), ('needs_renovation', 'Требует ремонта')], max_length=20, null=True, verbose_name='Состояние недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_usage',
            field=models.CharField(blank=True, choices=[('residential', 'Жилое'), ('commercial', 'Коммерческое'), ('industrial', 'Индустриальное')], max_length=20, null=True, verbose_name='Назначение недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего этажей'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='DomushnikApp.propertytype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='feature_name',
            field=models.CharField(max_length=100, verbose_name='Название характеристики'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='feature_value',
            field=models.CharField(max_length=255, verbose_name='Значение характеристики'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='DomushnikApp.property', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='photo',
            field=models.ImageField(upload_to='property_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='DomushnikApp.property', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='DomushnikApp.property', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='DomushnikApp.property', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DomushnikApp.purpose', verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='specific_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Особые требования'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
    ]
