# Generated by Django 4.2.16 on 2024-11-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DomushnikApp', '0003_remove_address_district_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Мебель'),
        ),
    ]
