# Generated by Django 4.2.16 on 2024-11-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DomushnikApp', '0004_alter_property_furnished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='nearby_amenities',
        ),
    ]
