# Generated by Django 4.2.16 on 2024-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DomushnikApp', '0008_alter_landlord_is_legal_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название недвижимости'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='file_path',
            field=models.CharField(max_length=255, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='property',
            name='energy_efficiency_class',
            field=models.CharField(blank=True, choices=[('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=10, null=True, verbose_name='Класс энергопотребления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('Газовый', 'Газовый'), ('Водяной', 'Водяной'), ('Электрический', 'Электрический')], max_length=50, null=True, verbose_name='Тип отопления'),
        ),
    ]
