# Generated by Django 4.2.16 on 2024-11-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DomushnikApp', '0009_property_property_name_alter_backup_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=255, verbose_name='Название недвижимости'),
        ),
    ]
