# Generated by Django 4.2.17 on 2024-12-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DomushnikApp', '0011_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DomushnikApp.address', verbose_name='Адрес'),
        ),
    ]
